name: flutter_base_architecture
description: A base Flutter architecture.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  get_it: ^7.2.0

  injectable: ^2.1.0
  provider: ^6.0.5
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  tuple: ^2.0.1
  collection: ^1.17.0
  dio: ^5.0.3
  json_annotation: ^4.8.0
  pretty_dio_logger: ^1.3.1
  connectivity_plus: ^3.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  injectable_generator: ^2.1.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Bold.ttf
        - asset: fonts/Rubik-Light.ttf
        - asset: fonts/Rubik-Medium.ttf
        - asset: fonts/Rubik-Regular.ttf
